# Generated by Django 5.2.13 on 2026-05-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_lostfounditem_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='contact_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='preferred_contact_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone')], default='whatsapp', help_text='Preferred contact method for communication', max_length=20),
        ),
    ]

