# Generated by Django 5.2.13 on 2026-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_claim_approved_at_claim_contact_shared_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfounditem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='status',
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
