# Generated by Django 5.2.13 on 2026-05-22 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfounditem',
            name='claimed',
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claim_pending', 'Claim Pending'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_description', models.TextField(help_text='Describe details that prove ownership')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone')], default='whatsapp', help_text='Preferred contact method for communication', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('contact_shared_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.lostfounditem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'claimant')},
            },
        ),
    ]

