# Generated by Django 5.2.13 on 2026-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_lostfounditem_claimed_lostfounditem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='dropoff_location',
            field=models.CharField(blank=True, choices=[('security', 'Security'), ('student_affairs', 'Student Affairs'), ('library', 'Library')], help_text='Where the item was dropped off (if any)', max_length=50, null=True),
        ),
    ]
